services:
  backend:
    build: ./backend/odc
    container_name: jenkins_backend_app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: jenkins_frontend_app
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: odc
      POSTGRES_PASSWORD: odc123
      POSTGRES_DB: odcdb
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build: ./backend/odc
    command: python manage.py migrate
    depends_on:
      - db
      - backend

volumes:
  postgres_data:



